using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
public static partial class Fix
{
  public const string PRACTICE_CLAW = "練習用の爪";
  public const string FINE_CLAW = "ファイン・クロー";
  public const string SURVIVAL_CLAW = "サバイバル・クロー";
  public const string RISING_FORCE_CLAW = "ライジング・フォース・クロー";
  public const string LIGHTNING_CLAW = "電光の爪";
  public const string PRACTICE_SWORD = "練習用の剣";
  public const string FINE_SWORD = "ファイン・ソード";
  public const string BRONZE_SWORD = "ブロンズ・ソード";
  public const string SWORD_OF_LIFE = "ソード・オブ・ライフ";
  public const string AERO_BLADE = "疾風の剣";
  public const string MERGIZD_SOL_BLADE = "Mergizd Sol Blade";
  public const string FINE_LANCE = "ファイン・ランス";
  public const string SHARP_LANCE = "シャープ・ランス";
  public const string WHITE_PARGE_LANCE = "ホワイトパージ・ランス";
  public const string ICE_SPIRIT_LANCE = "氷魂の槍";
  public const string FINE_AXE = "ファイン・アックス";
  public const string VIKING_AXE = "バイキング・アックス";
  public const string EARTH_POWER_AXE = "土力の斧";
  public const string WARWOLF_AXE = "ワーウルフ・アックス";
  public const string PRACTICE_ORB = "練習用のオーブ";
  public const string FINE_ORB = "ファイン・オーブ";
  public const string ENERGY_ORB = "エナジー・オーブ";
  public const string LIVING_GROWTH_ORB = "リビング・グロース・オーブ";
  public const string RED_PILLER_ORB = "炎柱の水晶玉";
  public const string FINE_ROD = "ファイン・ロッド";
  public const string WOOD_ROD = "ウッド・ロッド";
  public const string TOUGH_TREE_ROD = "頑丈な樫の杖";
  public const string BLACK_SORCERER_ROD = "ブラック・ソーサラー・ロッド";
  public const string FINE_BOOK = "ファイン・ブック";
  public const string KINDNESS_BOOK = "カインドネス・ブック";
  public const string SAINT_FAITHFUL_BOOK = "セイント・フェイスフル・ブック";
  public const string MUIN_BOOK = "無印の魔導書";
  public const string FINE_BOW = "ファイン・ボウ";
  public const string ELVISH_BOW = "エルヴィッシュ・ボウ";
  public const string ICICLE_LONGBOW = "アイシクル・ロングボウ";
  public const string MUMYOU_BOW = "無明の弓";
  public const string FINE_SHIELD = "ファイン・シールド";
  public const string KITE_SHIELD = "カイト・シールド";
  public const string SUPERIOR_FLAME_SHIELD = "スペリオル・フレイム・シールド";
  public const string BEGINNER_ARMOR = "初心者の鎧";
  public const string FINE_ARMOR = "ファイン・アーマー";
  public const string BEGINNER_CROSS = "初心者の舞踏衣";
  public const string FINE_CROSS = "ファイン・クロス";
  public const string BEGINNER_ROBE = "初心者のローブ";
  public const string FINE_ROBE = "ファイン・ローブ";
  public const string FLAT_SHOES = "フラット・シューズ";
  public const string COMPACT_EARRING = "コンパクト・イヤリング";
  public const string POWER_BANDANA = "パワー・バンダナ";
  public const string CHERRY_CHOKER = "チェリー・チョーカー";
  public const string RED_PENDANT = "レッド・ペンダント";
  public const string BLUE_PENDANT = "ブルー・ペンダント";
  public const string PURPLE_PENDANT = "パープル・ペンダント";
  public const string GREEN_PENDANT = "グリーン・ペンダント";
  public const string YELLOW_PENDANT = "イエロー・ペンダント";
  public const string BLUE_WIZARD_HAT = "ブルー・ウィザード・ハット";
  public const string FLAME_HAND_KEEPER = "フレイム・ハンド・キーパー";
  public const string SMALL_RED_POTION = "小さい赤ポーション";
  public const string ZETANIUM_STONE = "ゼタニウム鉱石";
  public const string FIELD_RESEARCH_LICENSE = "国内外遠征許可証";
  public const string ITEM_MATOCK = "マトック";
  public const string ITEM_TOOMI_AOSUISYOU = "遠見の青水晶";
  public const string PURE_CLEAN_WATER = "清透水";
  public const string RESIST_POISON_SUIT = "耐毒防護服";
  public const string ARTHARIUM_KEY = "アーサリウム工場跡地の鍵";
}
