using System;
using System.Collections.Generic;

/// <summary>
/// アイテム名の日英対応。
/// 以前は itemNameTable という L10n とは別のテーブルを持ち、明示登録が無いものは
/// Fix の定数名から機械生成した英語を返していた (ABSENCE_MOAI_JP -> "Absence Moai Jp" 等)。
/// 翻訳機構を L10n 一本にするため、明示登録をここへ移送し、機械生成は廃止した。
/// 未登録のアイテムは英語モードでも日本語のまま表示される (品質の低い英語を出すより安全)。
/// </summary>
public static partial class L10n
{
  /// <summary>
  /// アイテム名を登録する。日本語名そのものをキーとし、L10n の同一テーブルへ格納する。
  /// Item.DisplayName -> L10n.GetItemName -> GetDisplayName が、このキーで引く。
  /// </summary>
  private static void RegisterItemName(string japanese, string english)
  {
    if (string.IsNullOrEmpty(japanese)) { return; }
    Register(japanese, japanese, english);
  }

  internal static void RegisterItemNames()
  {
    // ---------------------------------------------------------------
    // Explicit JP→EN item name translations
    // tokens or otherwise misleading English are registered here first.
    // ---------------------------------------------------------------
    // --- Phase I-1: Esmilia Grassfield (weapons / accessories) ---
    RegisterItemName(Fix.MUMYOU_BOW, "Bow of Obscurity");
    RegisterItemName(Fix.RED_PILLER_ORB, "Flame Pillar Crystal");
    RegisterItemName(Fix.MUIN_BOOK, "Blank Grimoire");
    RegisterItemName(Fix.HINJAKU_RING, "Feeble Bangle");
    RegisterItemName(Fix.USUYOGORETA_FEATHER, "Grimy Feather Ornament");
    RegisterItemName(Fix.KUKEI_BANGLE, "Rectangular Bangle");
    RegisterItemName(Fix.SUTERARESHI_EMBLEM, "Forsaken Emblem");
    RegisterItemName(Fix.SHAPED_FINGERRING, "Well-Shaped Ring");
    // Copper bangles (COPPERRING_*)
    RegisterItemName(Fix.COPPERRING_TIGER, "Copper Bangle 'Tiger'");
    RegisterItemName(Fix.COPPERRING_DORPHINE, "Copper Bangle 'Dolphin'");
    RegisterItemName(Fix.COPPERRING_HORSE, "Copper Bangle 'Horse'");
    RegisterItemName(Fix.COPPERRING_BEAR, "Copper Bangle 'Bear'");
    RegisterItemName(Fix.COPPERRING_HAYABUSA, "Copper Bangle 'Falcon'");
    RegisterItemName(Fix.COPPERRING_OCTOPUS, "Copper Bangle 'Octopus'");
    RegisterItemName(Fix.COPPERRING_RABBIT, "Copper Bangle 'Rabbit'");
    RegisterItemName(Fix.COPPERRING_SPIDER, "Copper Bangle 'Spider'");
    RegisterItemName(Fix.COPPERRING_DEER, "Copper Bangle 'Deer'");
    RegisterItemName(Fix.COPPERRING_ELEPHANT, "Copper Bangle 'Elephant'");
    // --- Phase I-1: Anshet synthesis ---
    RegisterItemName(Fix.KOUKAKU_ARMOR, "Chitin Armor");
    // --- Phase I-2: Goratrum Cave ---
    RegisterItemName(Fix.SEKISOUJU_ROD, "Red Twin-Wielded Rod");
    RegisterItemName(Fix.MADAN_SHOOTING_STAR, "Magic Shot: Shooting Star");
    RegisterItemName(Fix.HUANTEI_RING, "Unstable Ring");
    RegisterItemName(Fix.USED_HQ_BOOTS, "Worn High-Quality Boots");
    // Bronze bangles (BRONZE_RING_*)
    RegisterItemName(Fix.BRONZE_RING_KIBA, "Bronze Bangle 'Fang'");
    RegisterItemName(Fix.BRONZE_RING_SASU, "Bronze Bangle 'Pierce'");
    RegisterItemName(Fix.BRONZE_RING_KU, "Bronze Bangle 'Run'");
    RegisterItemName(Fix.BRONZE_RING_NAGURI, "Bronze Bangle 'Strike'");
    RegisterItemName(Fix.BRONZE_RING_TOBI, "Bronze Bangle 'Fly'");
    RegisterItemName(Fix.BRONZE_RING_KARAMU, "Bronze Bangle 'Entwine'");
    RegisterItemName(Fix.BRONZE_RING_HANERU, "Bronze Bangle 'Leap'");
    RegisterItemName(Fix.BRONZE_RING_TORU, "Bronze Bangle 'Capture'");
    RegisterItemName(Fix.BRONZE_RING_MIRU, "Bronze Bangle 'See'");
    RegisterItemName(Fix.BRONZE_RING_KATAI, "Bronze Bangle 'Sturdy'");
    // Color brands
    RegisterItemName(Fix.RED_KOKUIN, "Red Brand");
    RegisterItemName(Fix.BLUE_KOKUIN, "Blue Brand");
    RegisterItemName(Fix.PURPLE_KOKUIN, "Purple Brand");
    RegisterItemName(Fix.GREEN_KOKUIN, "Green Brand");
    RegisterItemName(Fix.YELLOW_KOKUIN, "Yellow Brand");
    // Misc accessories (Goratrum)
    RegisterItemName(Fix.CLEAN_HEARBAND, "Clean Hair Band");
    RegisterItemName(Fix.FIVECOLOR_COMPASS, "Five-Color Compass");
    RegisterItemName(Fix.BURIED_DANZAIANGEL_STATUE, "Statue of the Buried Judgment Angel");
    RegisterItemName(Fix.LIGHT_HAKURUANGEL_STATUE, "Statue of the Radiant Jade Angel");
    // --- Phase I-2: Fazil synthesis ---
    RegisterItemName(Fix.DENDO_DRILL_AXE, "Electromagnetic Drill Axe");
    RegisterItemName(Fix.TETRA_EYE_BIGROD, "Tetra-Style Stacked-Eye Staff");
    // --- Phase II-1: Mystic Forest ---
    RegisterItemName(Fix.ENSHOUTOU, "Flame-Soaring Blade");
    // Junk talismans
    RegisterItemName(Fix.JUNK_TARISMAN_POISON, "Junk Talisman [Poison]");
    RegisterItemName(Fix.JUNK_TARISMAN_SILENCE, "Junk Talisman [Silence]");
    RegisterItemName(Fix.JUNK_TARISMAN_BIND, "Junk Talisman [Bind]");
    RegisterItemName(Fix.JUNK_TARISMAN_SLEEP, "Junk Talisman [Sleep]");
    RegisterItemName(Fix.JUNK_TARISMAN_STUN, "Junk Talisman [Stun]");
    RegisterItemName(Fix.JUNK_TARISMAN_PARALYZE, "Junk Talisman [Paralyze]");
    RegisterItemName(Fix.JUNK_TARISMAN_FROZEN, "Junk Talisman [Frozen]");
    RegisterItemName(Fix.JUNK_TARISMAN_FEAR, "Junk Talisman [Fear]");
    RegisterItemName(Fix.JUNK_TARISMAN_TEMPTATION, "Junk Talisman [Temptation]");
    RegisterItemName(Fix.JUNK_TARISMAN_SLOW, "Junk Talisman [Slow]");
    RegisterItemName(Fix.JUNK_TARISMAN_DIZZY, "Junk Talisman [Dizzy]");
    RegisterItemName(Fix.JUNK_TARISMAN_SLIP, "Junk Talisman [Bleed]");
    // Misc drop items (Mystic Forest)
    RegisterItemName(Fix.SIHAIRYU_SIKOTU, "Dragon Lord's Finger Bone");
    RegisterItemName(Fix.OLDGLORY_TREE_KAREHA, "Ancient Great Tree Dead Leaf");
    RegisterItemName(Fix.GALEWIND_KONSEKI, "Gale Wind's Trace");
    RegisterItemName(Fix.SIN_CRYSTAL_KAKERA, "Sin Crystal Fragment");
    RegisterItemName(Fix.EVERMIND_ZANSHI, "Ever-Mind Lingering Thought");
    // Misc accessories (Mystic Forest)
    RegisterItemName(Fix.SPIRIT_TUNOBUE, "Spirits' Horn Flute");
    RegisterItemName(Fix.ENSEMBLE_FEATHER_HUT, "Ensemble Feather Hat");
    RegisterItemName(Fix.MEIUN_PRISM_BOX, "Prism Box of Fate");
    RegisterItemName(Fix.SQUARE_SINNEN, "Square [Faith]");
    RegisterItemName(Fix.SQUARE_BLESTAR, "Square [Deliberation]");
    RegisterItemName(Fix.SQUARE_CHISEI, "Square [Wisdom]");
    RegisterItemName(Fix.SQUARE_SENREN, "Square [Refinement]");
    RegisterItemName(Fix.SQUARE_SAIKI, "Square [Brilliance]");
    RegisterItemName(Fix.SQUARE_TANREN, "Square [Tempering]");
    RegisterItemName(Fix.SQUARE_KOKOH, "Square [Solitude]");
    // --- Phase II-2: Tower of Ohran ---
    RegisterItemName(Fix.KODAIEIJU_GREEN_LEAF, "Ancient Great Tree Evergreen Leaf");
    RegisterItemName(Fix.TYORENSOU_ZANKYO_LANCE, "Twin-Butterfly Resonance Lance");
    // Magic stones
    RegisterItemName(Fix.RED_MASEKI, "Red Magic Stone");
    RegisterItemName(Fix.BLUE_MASEKI, "Blue Magic Stone");
    RegisterItemName(Fix.PURPLE_MASEKI, "Purple Magic Stone");
    RegisterItemName(Fix.GREEN_MASEKI, "Green Magic Stone");
    RegisterItemName(Fix.YELLOW_MASEKI, "Yellow Magic Stone");
    // Misc accessories (Tower of Ohran)
    RegisterItemName(Fix.STARAIR_FLOATING_STONE, "Starry Sky Floating Stone");
    RegisterItemName(Fix.LIGHTBRIGHT_FLOATING_STONE, "Holy Light Floating Stone");
    // --- Phase III-1: Velgus Sea Temple ---
    RegisterItemName(Fix.STRONG_FIRE_HELL_BASTARDAXE, "Forged Flame Hell Bastard Axe");
    RegisterItemName(Fix.GOLDWILL_DESCENT_SOWRD, "Gold Will Descent Sword");
    // Silver bangles (SILVER_RING_*)
    RegisterItemName(Fix.SILVER_RING_GOUKA, "Silver Bangle [Hellfire]");
    RegisterItemName(Fix.SILVER_RING_TSUNAMI, "Silver Bangle [Tsunami]");
    RegisterItemName(Fix.SILVER_RING_AKISAME, "Silver Bangle [Autumn Rain]");
    RegisterItemName(Fix.SILVER_RING_NEPPA, "Silver Bangle [Heat Wave]");
    RegisterItemName(Fix.SILVER_RING_RAIMEI, "Silver Bangle [Thunder]");
    RegisterItemName(Fix.SILVER_RING_FUBUKI, "Silver Bangle [Blizzard]");
    RegisterItemName(Fix.SILVER_RING_GENJITSU, "Silver Bangle [Parhelion]");
    RegisterItemName(Fix.SILVER_RING_TATSUMAKI, "Silver Bangle [Tornado]");
    RegisterItemName(Fix.SILVER_RING_SYUNIJI, "Silver Bangle [Primary Rainbow]");
    RegisterItemName(Fix.SILVER_RING_KAGEROU, "Silver Bangle [Heat Shimmer]");
    // Brillistones
    RegisterItemName(Fix.REDLIGHT_BRIGHTSTONE, "Red-Light Brillistone");
    RegisterItemName(Fix.BLUELIGHT_BRIGHTSTONE, "Blue-Light Brillistone");
    RegisterItemName(Fix.PURPLELIGHT_BRIGHTSTONE, "Purple-Light Brillistone");
    RegisterItemName(Fix.GREENLIGHT_BRIGHTSTONE, "Green-Light Brillistone");
    RegisterItemName(Fix.YELLOWLIGHT_BRIGHTSTONE, "Yellow-Light Brillistone");
    // Misc accessories (Velgus)
    RegisterItemName(Fix.ANGEL_CONTRACT_SHEET, "Angel's Contract");
    // --- Palmetysia synthesis ---
    RegisterItemName(Fix.HATENA_BIG_BOX, "Mystery Big Box");
    // --- Phase IV-2: Edelgarzen Castle ---
    RegisterItemName(Fix.SHINGETSUEN_CLAW, "Deep Moon Abyss Claw");
    RegisterItemName(Fix.JUNKEI_SHIKI_BOOK, "Pure Vista Four Seasons Book");
    RegisterItemName(Fix.SYOKO_PALESTRIDE_BOW, "Dawn Pale-Stride Bow");
    RegisterItemName(Fix.SHISO_GENSUI_KING_CROSS, "Founding Marshal's Garb [Royal]");
    RegisterItemName(Fix.DANZAI_ANGEL_TALISMAN, "Judgment Angel's Talisman");
    // Platinum bangles (PLATINUM_RING_*)
    RegisterItemName(Fix.PLATINUM_RING_1, "Platinum Bangle [White Tiger]");
    RegisterItemName(Fix.PLATINUM_RING_2, "Platinum Bangle [Valkyrie]");
    RegisterItemName(Fix.PLATINUM_RING_3, "Platinum Bangle [Nightmare]");
    RegisterItemName(Fix.PLATINUM_RING_4, "Platinum Bangle [Narasimha]");
    RegisterItemName(Fix.PLATINUM_RING_5, "Platinum Bangle [Vermilion Bird]");
    RegisterItemName(Fix.PLATINUM_RING_6, "Platinum Bangle [Ouroboros]");
    RegisterItemName(Fix.PLATINUM_RING_7, "Platinum Bangle [Nine-Tails]");
    RegisterItemName(Fix.PLATINUM_RING_8, "Platinum Bangle [Behemoth]");
    RegisterItemName(Fix.PLATINUM_RING_9, "Platinum Bangle [Azure Dragon]");
    RegisterItemName(Fix.PLATINUM_RING_10, "Platinum Bangle [Black Tortoise]");
    // Misc accessories (Edelgarzen)
    RegisterItemName(Fix.DARKNESS_COIN, "Dark Currency");
    RegisterItemName(Fix.BLACK_DRAGON_FEATHER, "Black Wing Dragon's Feather");
    // --- Quest / key items ---
    RegisterItemName(Fix.ITEM_MATOCK, "Mattock");
    RegisterItemName(Fix.ITEM_TOOMI_AOSUISYOU, "Far-Seeing Blue Crystal");
    RegisterItemName(Fix.ITEM_WALKING_ROPE, "Tightrope");
    RegisterItemName(Fix.ITEM_COPPER_KEY, "Copper Key");
    RegisterItemName(Fix.PURE_SINSEISUI, "Holy Water");
    RegisterItemName(Fix.PURE_VITALIRY_WATER, "Vitality Water");
    RegisterItemName(Fix.KODAIEIJU_EDA, "Ancient Great Tree Branch");
    RegisterItemName(Fix.KIGAN_OFUDA, "Prayer Talisman");
    RegisterItemName(Fix.VELGUS_KEY1, "Velgus Sea Temple Key [1]");
    RegisterItemName(Fix.VELGUS_KEY2, "Velgus Sea Temple Key [2]");
    RegisterItemName(Fix.VELGUS_KEY3, "Velgus Sea Temple Key [3]");
    RegisterItemName(Fix.VELGUS2_KEY1, "Velgus Sea Temple Key [Stillness]");
    RegisterItemName(Fix.VELGUS2_KEY2, "Velgus Sea Temple Key [Sprint]");
    RegisterItemName(Fix.VELGUS2_KEY3, "Velgus Sea Temple Key [Adaptation]");
    RegisterItemName(Fix.EDELGARZEN_KEY, "Edelgarzen Castle: Front Gate Key");
    RegisterItemName(Fix.EDELGARZEN_KEY1, "Edelgarzen Castle Key [Tenacity]");
    RegisterItemName(Fix.EDELGARZEN_KEY2, "Edelgarzen Castle Key [Will]");
    RegisterItemName(Fix.EDELGARZEN_KEY3, "Edelgarzen Castle Key [Non-Action]");
    RegisterItemName(Fix.EDELGARZEN_KEY4, "Edelgarzen Castle Key [Omniscience]");
    RegisterItemName(Fix.ZEMULGEARS, "Supreme Blade: Zemulgears");
    RegisterItemName(Fix.ARTIFACT_GENSEI, "Ancient Orb: Integrity");
    RegisterItemName(Fix.ARTIFACT_ZIHI, "Ancient Orb: Mercy");
    RegisterItemName(Fix.ARTIFACT_MUSOU, "Ancient Orb: Peerless");
    RegisterItemName(Fix.LEGENDARY_FELTUS, "Divine Blade: Feltusch");
    // --- Potions ---
    RegisterItemName(Fix.TOTAL_HIYAKU_KASSEI, "Composite Elixir [Activation]");
    RegisterItemName(Fix.TOTAL_HIYAKU_JOUSEI, "Composite Elixir [Purification]");
    RegisterItemName(Fix.SOUKAI_DRINK_SS, "Refreshing Drink [S&S]");
    RegisterItemName(Fix.TUUKAI_DRINK_DD, "Exhilarating Drink [D&D]");
    RegisterItemName(Fix.GOD_YORISHIRO_SOSEI, "God's Vessel [Resurrection]");
    RegisterItemName(Fix.TRADITIONAL_POTION_DATTOU, "Traditional Elixir [Escape]");
    RegisterItemName(Fix.TRADITIONAL_POTION_HEIGAN, "Traditional Elixir [Closed Eyes]");
    RegisterItemName(Fix.TEN_ON_MORI_MEGUMI, "Heaven's Grace, Forest's Blessing");
    RegisterItemName(Fix.KINDAN_TOKKOUYAKU, "Forbidden Special Medicine");
    RegisterItemName(Fix.SOUIN_HIYAKU_DISENCHANT, "Monastery Elixir [Dispel]");
    // --- Material drop items ---
    RegisterItemName(Fix.COMMON_MANTIS_TAIEKI, "Mantis Fluid");
    RegisterItemName(Fix.COMMON_GREEN_SIKISO, "Green Pigment");
    RegisterItemName(Fix.COMMON_KOKYU_LETHER_MATERIAL, "Kokyuu Leather Material");
    RegisterItemName(Fix.COMMON_KATAME_TREE, "Solid Wood Branch");
    RegisterItemName(Fix.COMMON_WARM_NO_KOUKAKU, "Worm Carapace");
    RegisterItemName(Fix.COMMON_YELLOW_TAIEKI, "Yellow Bodily Fluid");
    RegisterItemName(Fix.COMMON_TOGETOGE_GRASS, "Prickly Grass");
    RegisterItemName(Fix.COMMON_RED_HOUSI, "Red Spore");
    RegisterItemName(Fix.COMMON_DOKUSO_NEEDLE, "Poison-Component Needle");
    RegisterItemName(Fix.COMMON_HORSE_HIZUME, "Horse Hoof");
    RegisterItemName(Fix.COMMON_COLORFUL_BALL, "Chromatic Ball");
    RegisterItemName(Fix.COMMON_SHARP_HAHEN, "Sharp Fragment");
    RegisterItemName(Fix.COMMON_NEBARIKE_EKITAI, "Viscous Liquid");
    RegisterItemName(Fix.COMMON_USUGATA_ENBAN, "Thin Disk");
    RegisterItemName(Fix.COMMON_HASSYADAI, "Launch Platform");
    RegisterItemName(Fix.COMMON_KYOUTEN_X, "Scripture X");
    RegisterItemName(Fix.COMMON_BUYOBUYO_MOEKASU, "Soggy Ash Residue");
    RegisterItemName(Fix.COMMON_BAKUHA_CHAKKAZAI, "Explosive Igniter");
    RegisterItemName(Fix.COMMON_SEKKAIKOU, "Limestone Ore");
    RegisterItemName(Fix.COMMON_SANKAKU_STEEL, "Triangular Steel");
    RegisterItemName(Fix.COMMON_PURPLE_BOTTOLE, "Purple Vial");
    RegisterItemName(Fix.COMMON_BOAR_MOMONIKU, "Boar Thigh Meat");
    RegisterItemName(Fix.COMMON_SNAKE_EMPTYSHELL, "Snake Shed Skin");
    RegisterItemName(Fix.COMMON_DRYAD_RINPUN, "Dryad Scale Powder");
    RegisterItemName(Fix.COMMON_ELEMENTAL_KONA, "Spirit Powder");
    RegisterItemName(Fix.COMMON_DORO_YOUKAIEKI, "Thick Corrosive Liquid");
    RegisterItemName(Fix.COMMON_YOUKAI_MIKI, "Aura-Wreathed Trunk");
    RegisterItemName(Fix.COMMON_DANPEN_OF_GOFU, "Talisman Scrap");
    RegisterItemName(Fix.COMMON_GOTUGOTU_BIGTREE, "Rugged Large Tree");
    RegisterItemName(Fix.COMMON_HUGE_HOHONIKU, "Large Cheek Meat");
    RegisterItemName(Fix.COMMON_THREE_FEATHER, "Three-Blade Feather");
    RegisterItemName(Fix.COMMON_YELLOW_DOROTSUCHI, "Yellow Muddy Soil");
    RegisterItemName(Fix.COMMON_RED_DOROTSUCHI, "Red Muddy Soil");
    RegisterItemName(Fix.COMMON_AIRORIGIN_KIHO, "Void-Origin Air Bubble");
    RegisterItemName(Fix.COMMON_HENSYOKU_KOKE, "Discolored Moss");
    RegisterItemName(Fix.COMMON_KIRAMEKU_GOLDHORN, "Gleaming Golden Horn");
    RegisterItemName(Fix.COMMON_BIRD_OUGI, "Bird Fan");
    RegisterItemName(Fix.COMMON_MEGANE_MATERIAL, "Scholar's Glasses Material");
    RegisterItemName(Fix.COMMON_KITSUNE_TAIL, "Fox Tail");
    RegisterItemName(Fix.COMMON_WHITE_HIDUME, "White Hoof");
    RegisterItemName(Fix.COMMON_TOUMEI_KESSYO, "Colorless Crystal");
    RegisterItemName(Fix.COMMON_MUKAKOU_SEKIEI, "Unprocessed Quartz");
    RegisterItemName(Fix.COMMON_HOUDAN_SHARD, "Cannonball Fragment");
    RegisterItemName(Fix.COMMON_DAGGERFISH_UROKO, "Daggerfish Scale");
    RegisterItemName(Fix.COMMON_MANTA_HARA, "Manta Belly");
    RegisterItemName(Fix.COMMON_BLUE_MAGATAMA, "Blue Magatama");
    RegisterItemName(Fix.COMMON_KURIONE_ZOUMOTU, "Clione Innards");
    RegisterItemName(Fix.COMMON_RENEW_AKAMI, "Fresh Red Meat");
    RegisterItemName(Fix.COMMON_ROSE_SEKKAI, "Rose Limestone");
    RegisterItemName(Fix.COMMON_WASI_BLUE_FEATHER, "Eagle's Blue Feather");
    RegisterItemName(Fix.COMMON_HANTOUMEI_ROCK, "Semi-Transparent Pretty Stone");
    RegisterItemName(Fix.COMMON_EIGHTEIGHT_KUROSUMI, "Eight-Eight's Black Ink");
    RegisterItemName(Fix.COMMON_BLACK_GESO, "Blackened Squid Tentacle");
    RegisterItemName(Fix.COMMON_BIGAXE_TOP, "Tip of Giant Axe");
    RegisterItemName(Fix.COMMON_GANGAME_EGG, "Hardy Tortoise Egg");
    RegisterItemName(Fix.COMMON_KYOZIN_MUNENIKU, "Resilient Breast Meat");
    RegisterItemName(Fix.COMMON_NANAIRO_SYOKUSYU, "Seven-Colored Tentacle");
    RegisterItemName(Fix.COMMON_SEA_MO, "Deep-Sea Seaweed");
    RegisterItemName(Fix.COMMON_SERPENT_UROKO, "Serpent Scale");
    RegisterItemName(Fix.COMMON_AYASHII_NENNEKI_ITO, "Suspicious Viscous Thread");
    RegisterItemName(Fix.COMMON_GOTUGOTU_KARA, "Rugged Shell");
    RegisterItemName(Fix.COMMON_SOFT_BIG_HIRE, "Soft Large Fin");
    RegisterItemName(Fix.COMMON_TAIRYO_FISH, "Large School of Fish");
    RegisterItemName(Fix.COMMON_PUREWHITE_KIMO, "Pure White Liver");
    RegisterItemName(Fix.COMMON_SHRIMP_DOTAI, "Shrimp Body");
    RegisterItemName(Fix.COMMON_KOUSITUKA_MATERIAL, "Hardened Material");
    RegisterItemName(Fix.COMMON_AOSAME_UROKO, "Blue Shark Scale");
    RegisterItemName(Fix.COMMON_EMBLEM_KNIGHT, "Knights' Emblem");
    RegisterItemName(Fix.COMMON_BLACKSAME_TOOTH, "Black Shark Sword-Tooth");
    RegisterItemName(Fix.COMMON_MYSTERIOUS_KARA, "Mysteriously-Shaped Shell");
    RegisterItemName(Fix.COMMON_CURSED_ITO, "Cursed Thread");
    RegisterItemName(Fix.COMMON_CHINMI_FISH, "Exotic Seafood");
    RegisterItemName(Fix.COMMON_HUNTER_SEVEN_TOOL, "Hunter's Seven Tools");
    RegisterItemName(Fix.COMMON_BEAST_KEGAWA, "Wild Beast Hide");
    RegisterItemName(Fix.RARE_BLOOD_DAGGER_KAKERA, "Bloodstained Dagger Fragment");
    RegisterItemName(Fix.COMMON_SABI_BUGU, "Rusted Junk Weapon");
    RegisterItemName(Fix.COMMON_STEAM_POMP, "Steam Pump");
    RegisterItemName(Fix.COMMON_GOUKIN_MATERIAL, "Alloy Material");
    RegisterItemName(Fix.COMMON_KUMITATE_TENBIN_DOU, "Assembly Material: Scale Weight");
    RegisterItemName(Fix.COMMON_ONRYOU_HAKO, "Vengeful Spirit Box");
    RegisterItemName(Fix.RARE_CHAOS_SIZUKU, "Chaos Drop");
    RegisterItemName(Fix.RARE_DOOMBRINGER_KAKERA, "Doombringer Fragment");
    RegisterItemName(Fix.COMMON_KOKU_THUNDER_SIRUSI, "Engraved Thunder Mark");
    RegisterItemName(Fix.COMMON_TENNEN_JISYAKU, "Natural Magnet");
    RegisterItemName(Fix.COMMON_VOID_BOU, "Void Staff");
    RegisterItemName(Fix.COMMON_JUNKAN_MAHU_GU, "Circular Magic Sealing Tool");
    // --- Practice weapons ---
    RegisterItemName(Fix.PRACTICE_SWORD, "Practice Sword");
    RegisterItemName(Fix.PRACTICE_LANCE, "Practice Lance");
    RegisterItemName(Fix.PRACTICE_AXE, "Practice Axe");
    RegisterItemName(Fix.PRACTICE_CLAW, "Practice Claw");
    RegisterItemName(Fix.PRACTICE_ROD, "Practice Rod");
    RegisterItemName(Fix.PRACTICE_BOOK, "Practice Book");
    RegisterItemName(Fix.PRACTICE_ORB, "Practice Orb");
    RegisterItemName(Fix.PRACTICE_SHIELD, "Practice Shield");
    // --- Fine series ---
    RegisterItemName(Fix.FINE_SWORD, "Fine Sword");
    RegisterItemName(Fix.FINE_LANCE, "Fine Lance");
    RegisterItemName(Fix.FINE_AXE, "Fine Axe");
    RegisterItemName(Fix.FINE_CLAW, "Fine Claw");
    RegisterItemName(Fix.FINE_ROD, "Fine Rod");
    RegisterItemName(Fix.FINE_BOOK, "Fine Book");
    RegisterItemName(Fix.FINE_ORB, "Fine Orb");
    RegisterItemName(Fix.FINE_LARGE_SWORD, "Fine Greatsword");
    RegisterItemName(Fix.FINE_LARGE_LANCE, "Fine Grand Lance");
    RegisterItemName(Fix.FINE_LARGE_AXE, "Fine Grand Axe");
    RegisterItemName(Fix.FINE_BOW, "Fine Bow");
    RegisterItemName(Fix.FINE_LARGE_STAFF, "Fine Grand Staff");
    RegisterItemName(Fix.FINE_SHIELD, "Fine Shield");
    RegisterItemName(Fix.FINE_ARMOR, "Fine Armor");
    RegisterItemName(Fix.FINE_CROSS, "Fine Cross");
    RegisterItemName(Fix.FINE_ROBE, "Fine Robe");
    // --- Basic armor types ---
    RegisterItemName(Fix.HEAVY_ARMOR, "Heavy Armor");
    RegisterItemName(Fix.LEATHER_CROSS, "Leather Cross");
    RegisterItemName(Fix.COTTON_ROBE, "Cotton Robe");
    // --- Named early-game weapons and armor ---
    RegisterItemName(Fix.SURVIVAL_CLAW, "Survival Claw");
    RegisterItemName(Fix.RISING_FORCE_CLAW, "Rising Force Claw");
    RegisterItemName(Fix.LIGHTNING_CLAW, "Lightning Claw");
    RegisterItemName(Fix.BRONZE_SWORD, "Bronze Sword");
    RegisterItemName(Fix.SWORD_OF_LIFE, "Sword of Life");
    RegisterItemName(Fix.AERO_BLADE, "Gale Wind Blade");
    RegisterItemName(Fix.SHARP_LANCE, "Sharp Lance");
    RegisterItemName(Fix.WHITE_PARGE_LANCE, "White Purge Lance");
    RegisterItemName(Fix.ICE_SPIRIT_LANCE, "Ice Soul Lance");
    RegisterItemName(Fix.ICICLE_LONGBOW, "Icicle Longbow");
    RegisterItemName(Fix.VIKING_AXE, "Viking Axe");
    RegisterItemName(Fix.EARTH_POWER_AXE, "Earth Power Axe");
    RegisterItemName(Fix.WARWOLF_AXE, "Warwolf Axe");
    RegisterItemName(Fix.ENERGY_ORB, "Energy Orb");
    RegisterItemName(Fix.LIVING_GROWTH_ORB, "Living Growth Orb");
    RegisterItemName(Fix.WOOD_ROD, "Wood Rod");
    RegisterItemName(Fix.TOUGH_TREE_ROD, "Sturdy Oak Rod");
    RegisterItemName(Fix.BLACK_SORCERER_ROD, "Black Sorcerer's Rod");
    RegisterItemName(Fix.KINDNESS_BOOK, "Kindness Book");
    RegisterItemName(Fix.SAINT_FAITHFUL_BOOK, "Saint's Faithful Book");
    RegisterItemName(Fix.KITE_SHIELD, "Kite Shield");
    RegisterItemName(Fix.SUPERIOR_FLAME_SHIELD, "Superior Flame Shield");
    RegisterItemName(Fix.BEGINNER_ARMOR, "Novice's Armor");
    RegisterItemName(Fix.BEGINNER_CROSS, "Novice's Dance Garb");
    RegisterItemName(Fix.BEGINNER_ROBE, "Novice's Robe");
    // --- Early accessories ---
    RegisterItemName(Fix.NON_BRIGHT_ORB, "Dull Round Orb");
    RegisterItemName(Fix.ADJUSTABLE_BELT, "Adjusted Belt");
    RegisterItemName(Fix.BIRD_STATUE, "Bird Statue");
    RegisterItemName(Fix.REFRESHED_MANTLE, "Refreshing Mantle");
    RegisterItemName(Fix.COOL_CROWN, "Distinguished Crown");
    RegisterItemName(Fix.FLAT_SHOES, "Flat Shoes");
    RegisterItemName(Fix.AETHER_BALL, "Aether Ball");
    RegisterItemName(Fix.COMPACT_EARRING, "Compact Earring");
    RegisterItemName(Fix.POWER_BANDANA, "Power Bandana");
    RegisterItemName(Fix.CHERRY_CHOKER, "Cherry Choker");
    RegisterItemName(Fix.FIT_BANGLE, "Fit Bangle");
    RegisterItemName(Fix.PRISM_EMBLEM, "Prism Emblem");
    RegisterItemName(Fix.RED_PENDANT, "Red Pendant");
    RegisterItemName(Fix.BLUE_PENDANT, "Blue Pendant");
    RegisterItemName(Fix.PURPLE_PENDANT, "Purple Pendant");
    RegisterItemName(Fix.GREEN_PENDANT, "Green Pendant");
    RegisterItemName(Fix.YELLOW_PENDANT, "Yellow Pendant");
    RegisterItemName(Fix.WARRIOR_BRACER, "Warrior Bracer");
    RegisterItemName(Fix.STARDUST_CHARM, "Stardust Charm");
    RegisterItemName(Fix.BOLT_STONE, "Lightning Stone");
    RegisterItemName(Fix.ANTIDOTE_STONE, "Antidote Stone");
    RegisterItemName(Fix.SPIRIT_BRANCH, "Spirit Branch");
    RegisterItemName(Fix.BLUE_WIZARD_HAT, "Blue Wizard Hat");
    RegisterItemName(Fix.FLAME_HAND_KEEPER, "Flame Hand Keeper");
    RegisterItemName(Fix.WOLF_CROSS, "Wolf-Crafted Dance Garb");
    RegisterItemName(Fix.STRIDE_WAR_SWORD, "Stride War Sword");
    // --- Classical series ---
    RegisterItemName(Fix.CLASSICAL_SWORD, "Classical Sword");
    RegisterItemName(Fix.CLASSICAL_LANCE, "Classical Lance");
    RegisterItemName(Fix.CLASSICAL_AXE, "Classical Axe");
    RegisterItemName(Fix.CLASSICAL_CLAW, "Classical Claw");
    RegisterItemName(Fix.CLASSICAL_ROD, "Classical Rod");
    RegisterItemName(Fix.CLASSICAL_BOOK, "Classical Book");
    RegisterItemName(Fix.CLASSICAL_ORB, "Classical Orb");
    RegisterItemName(Fix.CLASSICAL_LARGE_SWORD, "Classical Greatsword");
    RegisterItemName(Fix.CLASSICAL_LARGE_LANCE, "Classical Grand Lance");
    RegisterItemName(Fix.CLASSICAL_LARGE_AXE, "Classical Grand Axe");
    RegisterItemName(Fix.CLASSICAL_BOW, "Classical Bow");
    RegisterItemName(Fix.CLASSICAL_LARGE_STAFF, "Classical Grand Staff");
    RegisterItemName(Fix.CLASSICAL_SHIELD, "Classical Shield");
    RegisterItemName(Fix.CLASSICAL_ARMOR, "Classical Armor");
    RegisterItemName(Fix.CLASSICAL_CROSS, "Classical Cross");
    RegisterItemName(Fix.CLASSICAL_ROBE, "Classical Robe");
    // --- Named mid-tier weapons and armor ---
    RegisterItemName(Fix.SMASH_BLADE, "Smash Blade");
    RegisterItemName(Fix.STYLISH_LANCE, "Stylish Lance");
    RegisterItemName(Fix.LAND_AXE, "Land Axe");
    RegisterItemName(Fix.SAVAGE_CLAW, "Savage Claw");
    RegisterItemName(Fix.WINGED_ROD, "Winged Rod");
    RegisterItemName(Fix.EXPERT_BOOK, "Expert Book");
    RegisterItemName(Fix.FLOATING_ORB, "Floating Orb");
    RegisterItemName(Fix.ELVISH_BOW, "Elvish Bow");
    RegisterItemName(Fix.IRON_SHIELD, "Iron Shield");
    RegisterItemName(Fix.IRON_ARMOR, "Iron Armor");
    RegisterItemName(Fix.CROSSCHAIN_MAIL, "Crosschain Mail");
    RegisterItemName(Fix.CHIFFON_ROBE, "Chiffon Robe");
    // --- Named upper-tier weapons and armor ---
    RegisterItemName(Fix.BLUE_LIGHTNING_SWORD, "Blue Lightning Sword");
    RegisterItemName(Fix.ASH_EXCLUDE_LANCE, "Ash Exclude Lance");
    RegisterItemName(Fix.BONE_CRUSH_AXE, "Bone Crush Axe");
    RegisterItemName(Fix.COLD_SPLASH_CLAW, "Cold Splash Claw");
    RegisterItemName(Fix.GORGON_EYES_BOOK, "Gorgon Eyes Book");
    RegisterItemName(Fix.STAR_FUSION_ORB, "Star Fusion Orb");
    RegisterItemName(Fix.SILVER_EARTH_SHIELD, "Silver Earth Shield");
    RegisterItemName(Fix.ROIZ_IMPERIAL_ARMOR, "Roiz Imperial Armor");
    RegisterItemName(Fix.SWIFT_THUNDER_CROSS, "Swift Thunder Cross");
    RegisterItemName(Fix.CROWD_DIRGE_ROBE, "Crowd Dirge Robe");
    RegisterItemName(Fix.DEPRESS_FEATHER, "Depress Feather");
    RegisterItemName(Fix.STIFF_BELT, "Tight Belt");
    RegisterItemName(Fix.LOST_NAME_EMBLEM, "Emblem of the Lost Name");
    RegisterItemName(Fix.DAMAGED_STATUE, "Damaged Statue");
    RegisterItemName(Fix.MAGICLIGHT_FIRE, "Magiclight [Fire]");
    RegisterItemName(Fix.MAGICLIGHT_ICE, "Magiclight [Ice]");
    RegisterItemName(Fix.MAGICLIGHT_SHADOW, "Magiclight [Shadow]");
    RegisterItemName(Fix.MAGICLIGHT_LIGHT, "Magiclight [Light]");
    RegisterItemName(Fix.RED_AMULET, "Red Amulet");
    RegisterItemName(Fix.BLUE_AMULET, "Blue Amulet");
    RegisterItemName(Fix.PURPLE_AMULET, "Purple Amulet");
    RegisterItemName(Fix.GREEN_AMULET, "Green Amulet");
    RegisterItemName(Fix.YELLOW_AMULET, "Yellow Amulet");
    RegisterItemName(Fix.STEEL_ANKLET, "Steel Anklet");
    RegisterItemName(Fix.TRUTH_GLASSES, "Glasses of Truth");
    RegisterItemName(Fix.ZEPHYR_FEATHER_BLUE, "Zephyr Feather [Blue]");
    RegisterItemName(Fix.CRIMSON_GAUNTLET, "Crimson Gauntlet");
    RegisterItemName(Fix.JADE_NOBLE_CIRCLET, "Jade Noble Circlet");
    RegisterItemName(Fix.ATTACH_SPIRAL_ORB, "Wearable Spiral Orb");
    RegisterItemName(Fix.THIN_STEEL_BUCKLER, "Thin Steel Buckler");
    // --- Smart series ---
    RegisterItemName(Fix.SMART_SWORD, "Smart Sword");
    RegisterItemName(Fix.SMART_LANCE, "Smart Lance");
    RegisterItemName(Fix.SMART_AXE, "Smart Axe");
    RegisterItemName(Fix.SMART_CLAW, "Smart Claw");
    RegisterItemName(Fix.SMART_ROD, "Smart Rod");
    RegisterItemName(Fix.SMART_BOOK, "Smart Book");
    RegisterItemName(Fix.SMART_ORB, "Smart Orb");
    RegisterItemName(Fix.SMART_LARGE_SWORD, "Smart Greatsword");
    RegisterItemName(Fix.SMART_LARGE_LANCE, "Smart Grand Lance");
    RegisterItemName(Fix.SMART_LARGE_AXE, "Smart Grand Axe");
    RegisterItemName(Fix.SMART_BOW, "Smart Bow");
    RegisterItemName(Fix.SMART_LARGE_STAFF, "Smart Grand Staff");
    RegisterItemName(Fix.SMART_SHIELD, "Smart Shield");
    RegisterItemName(Fix.SMART_ARMOR, "Smart Armor");
    RegisterItemName(Fix.SMART_CROSS, "Smart Cross");
    RegisterItemName(Fix.SMART_ROBE, "Smart Robe");
    // --- Named weapons and armor (second tier) ---
    RegisterItemName(Fix.DANCING_CLAW, "Dancing Claw");
    RegisterItemName(Fix.CUTTING_BLADE, "Cutting Blade");
    RegisterItemName(Fix.SWIFT_SPEAR, "Swift Spear");
    RegisterItemName(Fix.POWERED_AXE, "Powered Axe");
    RegisterItemName(Fix.LONG_BOW, "Longbow");
    RegisterItemName(Fix.AUTUMN_ROD, "Autumn Rod");
    RegisterItemName(Fix.BULKY_BOOK, "Bulky Book");
    RegisterItemName(Fix.FOCUS_ORB, "Focus Orb");
    RegisterItemName(Fix.WIDE_BUCKLER, "Wide Buckler");
    RegisterItemName(Fix.GOTHIC_PLATE, "Gothic Plate");
    RegisterItemName(Fix.FITNESS_CROSS, "Fitness Cross");
    RegisterItemName(Fix.SILK_ROBE, "Silk Robe");
    RegisterItemName(Fix.GALLANT_FEATHER_LANCE, "Gallant Feather Lance");
    RegisterItemName(Fix.THUNDER_BREAK_AXE, "Thunder Break Axe");
    RegisterItemName(Fix.WRATH_SABEL_CLAW, "Wrath Saber Claw");
    RegisterItemName(Fix.DORN_NAMELESS_ROD, "Dorn Nameless Rod");
    RegisterItemName(Fix.FINESSE_IMPERIAL_BOOK, "Finesse Imperial Book");
    RegisterItemName(Fix.INTRINSIC_FROZEN_ORB, "Intrinsic Frozen Orb");
    RegisterItemName(Fix.FORCEFUL_BASTARD_SWORD, "Forceful Bastard Sword");
    RegisterItemName(Fix.SHARPNEL_ARC_LANCER, "Shrapnel Arc Lancer");
    RegisterItemName(Fix.OGRE_KILL_BUSTER, "Ogre Kill Buster");
    RegisterItemName(Fix.EXPLODING_ASH_BOW, "Exploding Ash Bow");
    RegisterItemName(Fix.EARTH_POWERED_STAFF, "Earth Powered Staff");
    RegisterItemName(Fix.BLACK_REFLECTOR_SHIELD, "Black Reflector Shield");
    RegisterItemName(Fix.ARANDEL_FORCE_ARMOR, "Arandel Force Armor");
    RegisterItemName(Fix.WONDERING_BLESSED_CROSS, "Wandering Blessed Cross");
    RegisterItemName(Fix.SERANA_BRILLIANT_ROBE, "Serana Brilliant Robe");
    RegisterItemName(Fix.SUNLEAF_SEAL, "Sunleaf Seal");
    RegisterItemName(Fix.DEPLETH_SEED_PIERCE, "Depleth Seed Pierce");
    RegisterItemName(Fix.SPARKLINE_EMBLEM, "Sparkline Emblem");
    RegisterItemName(Fix.CHAINSHIFT_BOOTS, "Chainshift Boots");
    RegisterItemName(Fix.ASHED_COMPASS, "Ashed Compass");
    RegisterItemName(Fix.MIRAGE_PLASMA_EARRING, "Mirage Plasma Earring");
    RegisterItemName(Fix.PHOTON_ZEAL_CROWN, "Photon Zeal Crown");
    RegisterItemName(Fix.DEMONS_STAR_BRACELET, "Demon's Star Bracelet");
    RegisterItemName(Fix.MIST_WAVE_GAUNTLET, "Mist Wave Gauntlet");
    RegisterItemName(Fix.SPIRIT_CHALICE_OF_HEART, "Spirit Chalice of Heart");
    RegisterItemName(Fix.VIRGIRANTE_HELLGATE_LANCE, "Virgirante Hellgate Lance");
    RegisterItemName(Fix.MULLERHAIZEN_AGARTA_BOOK, "Mullerhaizen Book of Agarta");
    RegisterItemName(Fix.SILENT_OLGA_CLAW, "Silent Olga Claw");
    RegisterItemName(Fix.IRIDESCENT_CLOUD_FEATHER, "Iridescent Cloud Feather");
    RegisterItemName(Fix.BRINSCALE_WAR_CROSS, "Brinscale War Cross");
    RegisterItemName(Fix.GREAT_COMPOSITE_LANCE, "Great Composite Lance");
    // --- Superior series ---
    RegisterItemName(Fix.SUPERIOR_SWORD, "Superior Sword");
    RegisterItemName(Fix.SUPERIOR_LANCE, "Superior Lance");
    RegisterItemName(Fix.SUPERIOR_AXE, "Superior Axe");
    RegisterItemName(Fix.SUPERIOR_CLAW, "Superior Claw");
    RegisterItemName(Fix.SUPERIOR_ROD, "Superior Rod");
    RegisterItemName(Fix.SUPERIOR_BOOK, "Superior Book");
    RegisterItemName(Fix.SUPERIOR_ORB, "Superior Orb");
    RegisterItemName(Fix.SUPERIOR_LARGE_SWORD, "Superior Greatsword");
    RegisterItemName(Fix.SUPERIOR_LARGE_LANCE, "Superior Grand Lance");
    RegisterItemName(Fix.SUPERIOR_LARGE_AXE, "Superior Grand Axe");
    RegisterItemName(Fix.SUPERIOR_BOW, "Superior Bow");
    RegisterItemName(Fix.SUPERIOR_LARGE_STAFF, "Superior Grand Staff");
    RegisterItemName(Fix.SUPERIOR_SHIELD, "Superior Shield");
    RegisterItemName(Fix.SUPERIOR_ARMOR, "Superior Armor");
    RegisterItemName(Fix.SUPERIOR_CROSS, "Superior Cross");
    RegisterItemName(Fix.SUPERIOR_ROBE, "Superior Robe");
    // --- Named high-tier weapons and armor ---
    RegisterItemName(Fix.FULLMETAL_ASTRAL_BLADE, "Fullmetal Astral Blade");
    RegisterItemName(Fix.STORM_FURY_LANCER, "Storm Fury Lancer");
    RegisterItemName(Fix.WARLOAD_BASTARD_AXE, "Warlord Bastard Axe");
    RegisterItemName(Fix.EARTH_SHARD_CLAW, "Earth Shard Claw");
    RegisterItemName(Fix.ENGAGED_FUTURE_ROD, "Engaged Future Rod");
    RegisterItemName(Fix.ANCIENT_FAITHFUL_BOOK, "Ancient Faithful Book");
    RegisterItemName(Fix.BLUE_SKY_ORB, "Blue Sky Orb");
    RegisterItemName(Fix.PRISMATIC_SOUL_BREAKER, "Prismatic Soul Breaker");
    RegisterItemName(Fix.BLOOD_STUBBORN_SPEAR, "Blood Stubborn Spear");
    RegisterItemName(Fix.ELEMENTAL_DISRUPT_AXE, "Elemental Disrupt Axe");
    RegisterItemName(Fix.LINGERING_FROST_SHOOTER, "Lingering Frost Shooter");
    RegisterItemName(Fix.INFERNAL_IMMORTAL_STAFF, "Infernal Immortal Staff");
    RegisterItemName(Fix.GRACEFUL_KINGS_BUCKLER, "Graceful King's Buckler");
    RegisterItemName(Fix.HARDED_INTENSITY_PLATE, "Hardened Intensity Plate");
    RegisterItemName(Fix.SOLDIER_HATRED_CROSS, "Soldier Vigor Cross");
    RegisterItemName(Fix.WONDERERS_INVISIBLE_ROBE, "Wanderer's Invisible Robe");
    RegisterItemName(Fix.ZELMAN_THE_ONSLAUGHT_BASTER, "Zelman the Onslaught Buster");
    RegisterItemName(Fix.LIFEGRACE_FORTUNE_STAFF, "Lifegrace Fortune Staff");
    RegisterItemName(Fix.WHITEVEIL_QUEENS_ROBE, "Whiteveil Queen's Robe");
    // --- Steel bangles ---
    RegisterItemName(Fix.STEEL_RING_POWER, "Steel Bangle 'Power'");
    RegisterItemName(Fix.STEEL_RING_SENSE, "Steel Bangle 'Sense'");
    RegisterItemName(Fix.STEEL_RING_TOUGH, "Steel Bangle 'Tough'");
    RegisterItemName(Fix.STEEL_RING_ROCK, "Steel Bangle 'Rock'");
    RegisterItemName(Fix.STEEL_RING_FAST, "Steel Bangle 'Fast'");
    RegisterItemName(Fix.STEEL_RING_SHARP, "Steel Bangle 'Sharp'");
    RegisterItemName(Fix.STEEL_RING_HIGH, "Steel Bangle 'High'");
    RegisterItemName(Fix.STEEL_RING_DEEP, "Steel Bangle 'Deep'");
    RegisterItemName(Fix.STEEL_RING_BOUND, "Steel Bangle 'Bound'");
    RegisterItemName(Fix.STEEL_RING_EMOTE, "Steel Bangle 'Emote'");
    // --- Powersteel bangles ---
    RegisterItemName(Fix.POWER_STEEL_RING_SOLID, "Powersteel Bangle 'Solid'");
    RegisterItemName(Fix.POWER_STEEL_RING_VAPOUR, "Powersteel Bangle 'Vapour'");
    RegisterItemName(Fix.POWER_STEEL_RING_STRAIN, "Powersteel Bangle 'Strain'");
    RegisterItemName(Fix.POWER_STEEL_RING_TOLERANCE, "Powersteel Bangle 'Tolerance'");
    RegisterItemName(Fix.POWER_STEEL_RING_ASCEND, "Powersteel Bangle 'Ascend'");
    RegisterItemName(Fix.POWER_STEEL_RING_INTERCEPT, "Powersteel Bangle 'Intercept'");
    // --- Unique accessories ---
    RegisterItemName(Fix.LUMINOUS_REFLECT_MIRROR, "Luminous Reflect Mirror");
    RegisterItemName(Fix.BLACK_SPIRAL_NEEDLE, "Black Spiral Needle");
    RegisterItemName(Fix.EMBLEM_OF_VALKYRIE, "Emblem of Valkyrie");
    RegisterItemName(Fix.EMBLEM_OF_NECROMANCY, "Emblem of Necromancy");
    RegisterItemName(Fix.OHRAN_REDIAN_ROD, "Ohran Redian Rod");
    RegisterItemName(Fix.VIGILANT_FENCER_ROBE, "Vigilant Fencer's Robe");
    RegisterItemName(Fix.LION_EYES_BLADE, "Lion Eyes Blade");
    // --- Master series ---
    RegisterItemName(Fix.MASTER_SWORD, "Master Sword");
    RegisterItemName(Fix.MASTER_LANCE, "Master Lance");
    RegisterItemName(Fix.MASTER_AXE, "Master Axe");
    RegisterItemName(Fix.MASTER_CLAW, "Master Claw");
    RegisterItemName(Fix.MASTER_ROD, "Master Rod");
    RegisterItemName(Fix.MASTER_BOOK, "Master Book");
    RegisterItemName(Fix.MASTER_ORB, "Master Orb");
    RegisterItemName(Fix.MASTER_LARGE_SWORD, "Master Greatsword");
    RegisterItemName(Fix.MASTER_LARGE_LANCE, "Master Grand Lance");
    RegisterItemName(Fix.MASTER_LARGE_AXE, "Master Grand Axe");
    RegisterItemName(Fix.MASTER_BOW, "Master Bow");
    RegisterItemName(Fix.MASTER_LARGE_STAFF, "Master Grand Staff");
    RegisterItemName(Fix.MASTER_SHIELD, "Master Shield");
    RegisterItemName(Fix.MASTER_ARMOR, "Master Armor");
    RegisterItemName(Fix.MASTER_CROSS, "Master Cross");
    RegisterItemName(Fix.MASTER_ROBE, "Master Robe");
    // --- Named elite weapons and armor ---
    RegisterItemName(Fix.SOLEMN_EMPERORS_SWORD, "Solemn Emperor's Sword");
    RegisterItemName(Fix.MYSTIC_BLUE_JAVELIN, "Mystic Blue Javelin");
    RegisterItemName(Fix.AURA_BURN_CLAW, "Aura Burn Claw");
    RegisterItemName(Fix.MIND_STONEFEAR_ROD, "Mind Stonefear Rod");
    RegisterItemName(Fix.DARKSUN_TRAGEDIC_BOOK, "Darksun Tragedic Book");
    RegisterItemName(Fix.CHROMATIC_FORGE_ORB, "Chromatic Forge Orb");
    RegisterItemName(Fix.FLASH_VANISH_SPEAR, "Flash Vanish Spear");
    RegisterItemName(Fix.VOLCANIC_BATTLE_BASTER, "Volcanic Battle Buster");
    RegisterItemName(Fix.WHITE_FIRE_CROSSBOW, "White Fire Crossbow");
    RegisterItemName(Fix.ELDERSTAFF_OF_LIFEBLOOM, "Elderstaff of Lifebloom");
    RegisterItemName(Fix.DIMENSION_ZERO_SHIELD, "Dimension Zero Shield");
    RegisterItemName(Fix.HIGHWARRIOR_DRAGONMAIL, "High Warrior Dragonmail");
    RegisterItemName(Fix.SWIFTCROSS_OF_REDTHUNDER, "Swiftcross of Red Thunder");
    RegisterItemName(Fix.BLADESHADOW_CROWDED_DRESS, "Bladeshadow Crowded Dress");
    RegisterItemName(Fix.BLACKROGUE_BLACKROGUE_AMBIDEXTARITY_DAGGER, "Blackrogue Ambidexterity Dagger");
    RegisterItemName(Fix.HOLY_BLESSING_SHIELD, "Holy Blessing Shield");
    RegisterItemName(Fix.LATA_GUARDIAN_RING, "Guardian Ring [Lata's Guidance]");
    RegisterItemName(Fix.BLUEEYE_TEMPLE_PENDANT, "Temple Knight's Pendant [Blue Eye]");
    RegisterItemName(Fix.REDEYE_TEMPLE_PENDANT, "Temple Knight's Pendant [Red Eye]");
    RegisterItemName(Fix.SEAL_OF_REDEYE, "Seal of Red Eye");
    RegisterItemName(Fix.SEAL_OF_BLUEEYE, "Seal of Blue Eye");
    RegisterItemName(Fix.WINGED_LIGHTNING_BOOTS, "Winged Lightning Boots");
    RegisterItemName(Fix.SPELLCASTERS_LENS, "Spellcaster's Lens");
    RegisterItemName(Fix.PEACEFUL_REBIRTH_CANDLE, "Peaceful Rebirth Candle");
    RegisterItemName(Fix.DESPAIR_BLACKANGEL_RING, "Despair Black Angel Ring");
    RegisterItemName(Fix.PHANTASMAL_INSIGHT_RUNE, "Phantasmal Insight Rune");
    RegisterItemName(Fix.SILVER_ETERNAL_SEED, "Silver Eternal Seed");
    RegisterItemName(Fix.FIRELIEGE_AETHER_TALISMAN, "Fireliege Aether Talisman");
    RegisterItemName(Fix.RAINBOW_MOON_COMPASS, "Rainbow Moon Compass");
    RegisterItemName(Fix.HIGH_RANGER_BATTLE_BOW, "High Ranger Battle Bow");
    RegisterItemName(Fix.DARMEKIUS_HARD_PLATE, "Darmekius Hard Plate");
    RegisterItemName(Fix.SEE_SONG_FEBRIOL_BOOK, "See Song Febriol Book");
    // --- Marvelous series ---
    RegisterItemName(Fix.MARVELOUS_SWORD, "Marvelous Sword");
    RegisterItemName(Fix.MARVELOUS_LANCE, "Marvelous Lance");
    RegisterItemName(Fix.MARVELOUS_AXE, "Marvelous Axe");
    RegisterItemName(Fix.MARVELOUS_CLAW, "Marvelous Claw");
    RegisterItemName(Fix.MARVELOUS_ROD, "Marvelous Rod");
    RegisterItemName(Fix.MARVELOUS_BOOK, "Marvelous Book");
    RegisterItemName(Fix.MARVELOUS_ORB, "Marvelous Orb");
    RegisterItemName(Fix.MARVELOUS_LARGE_SWORD, "Marvelous Greatsword");
    RegisterItemName(Fix.MARVELOUS_LARGE_LANCE, "Marvelous Grand Lance");
    RegisterItemName(Fix.MARVELOUS_LARGE_AXE, "Marvelous Grand Axe");
    RegisterItemName(Fix.MARVELOUS_BOW, "Marvelous Bow");
    RegisterItemName(Fix.MARVELOUS_LARGE_STAFF, "Marvelous Grand Staff");
    RegisterItemName(Fix.MARVELOUS_SHIELD, "Marvelous Shield");
    RegisterItemName(Fix.MARVELOUS_ARMOR, "Marvelous Armor");
    RegisterItemName(Fix.MARVELOUS_CROSS, "Marvelous Cross");
    RegisterItemName(Fix.MARVELOUS_ROBE, "Marvelous Robe");
    // --- Excellent series ---
    RegisterItemName(Fix.EXCELLENT_SWORD, "Excellent Sword");
    RegisterItemName(Fix.EXCELLENT_LANCE, "Excellent Lance");
    RegisterItemName(Fix.EXCELLENT_AXE, "Excellent Axe");
    RegisterItemName(Fix.EXCELLENT_CLAW, "Excellent Claw");
    RegisterItemName(Fix.EXCELLENT_ROD, "Excellent Rod");
    RegisterItemName(Fix.EXCELLENT_BOOK, "Excellent Book");
    RegisterItemName(Fix.EXCELLENT_ORB, "Excellent Orb");
    RegisterItemName(Fix.EXCELLENT_LARGE_SWORD, "Excellent Greatsword");
    RegisterItemName(Fix.EXCELLENT_LARGE_LANCE, "Excellent Grand Lance");
    RegisterItemName(Fix.EXCELLENT_LARGE_AXE, "Excellent Grand Axe");
    RegisterItemName(Fix.EXCELLENT_BOW, "Excellent Bow");
    RegisterItemName(Fix.EXCELLENT_LARGE_STAFF, "Excellent Grand Staff");
    RegisterItemName(Fix.EXCELLENT_SHIELD, "Excellent Shield");
    RegisterItemName(Fix.EXCELLENT_ARMOR, "Excellent Armor");
    RegisterItemName(Fix.EXCELLENT_CROSS, "Excellent Cross");
    RegisterItemName(Fix.EXCELLENT_ROBE, "Excellent Robe");
    // --- Extreme series ---
    RegisterItemName(Fix.EXTREME_SWORD, "Extreme Sword");
    RegisterItemName(Fix.EXTREME_LANCE, "Extreme Lance");
    RegisterItemName(Fix.EXTREME_AXE, "Extreme Axe");
    RegisterItemName(Fix.EXTREME_CLAW, "Extreme Claw");
    RegisterItemName(Fix.EXTREME_ROD, "Extreme Rod");
    RegisterItemName(Fix.EXTREME_BOOK, "Extreme Book");
    RegisterItemName(Fix.EXTREME_ORB, "Extreme Orb");
    RegisterItemName(Fix.EXTREME_BOW, "Extreme Bow");
    RegisterItemName(Fix.EXTREME_LARGE_STAFF, "Extreme Grand Staff");
    RegisterItemName(Fix.EXTREME_SHIELD, "Extreme Shield");
    RegisterItemName(Fix.EXTREME_ARMOR, "Extreme Armor");
    RegisterItemName(Fix.EXTREME_CROSS, "Extreme Cross");
    RegisterItemName(Fix.EXTREME_ROBE, "Extreme Robe");
    // --- Named legendary weapons and armor ---
    RegisterItemName(Fix.ETHEREAL_EDGE_BLADE, "Ethereal Edge Blade");
    RegisterItemName(Fix.EVIL_ELIMINATION_LANCE, "Evil Elimination Lance");
    RegisterItemName(Fix.PRISON_DESTRUCTION_AXE, "Prison Destruction Axe");
    RegisterItemName(Fix.GARGAN_BLAZE_ROD, "Gargan Blaze Rod");
    RegisterItemName(Fix.ALL_ELEMENTAL_ORB, "All Elemental Orb");
    RegisterItemName(Fix.LABYRINTH_MAGE_BLUESTAFF, "Labyrinth Mage's Blue Grand Staff");
    RegisterItemName(Fix.MAJESTIC_FORCE_SHIELD, "Majestic Force Shield");
    RegisterItemName(Fix.ROBE_OF_COLORSTREAMING, "Robe of Colorstreaming");
    // --- Crystals ---
    RegisterItemName(Fix.RED_CRYSTAL, "Crimson Crystal");
    RegisterItemName(Fix.BLUE_CRYSTAL, "Lapis Crystal");
    RegisterItemName(Fix.PURPLE_CRYSTAL, "Violet Crystal");
    RegisterItemName(Fix.GREEN_CRYSTAL, "Jade Crystal");
    RegisterItemName(Fix.YELLOW_CRYSTAL, "Amber Crystal");
    // --- Late-game accessories ---
    RegisterItemName(Fix.RAGING_RESONANCE_RING, "Raging Resonance Ring");
    RegisterItemName(Fix.LAGINA_DISTORTED_BRACER, "Lagina Distorted Bracer");
    RegisterItemName(Fix.RIGID_WAVE_METALGUNTLET, "Rigid Wave Metal Gauntlet");
    RegisterItemName(Fix.ISOCHRON_FATED_LENS, "Isochron Fated Lens");
    RegisterItemName(Fix.HEART_SEEKERS_STONE, "Heart Seeker's Stone");
    RegisterItemName(Fix.SUN_BREAKERS_STONE, "Sun Breaker's Stone");
    // --- Incredible series ---
    RegisterItemName(Fix.INCREDIBLE_SWORD, "Incredible Sword");
    RegisterItemName(Fix.INCREDIBLE_LANCE, "Incredible Lance");
    RegisterItemName(Fix.INCREDIBLE_AXE, "Incredible Axe");
    RegisterItemName(Fix.INCREDIBLE_CLAW, "Incredible Claw");
    RegisterItemName(Fix.INCREDIBLE_ROD, "Incredible Rod");
    RegisterItemName(Fix.INCREDIBLE_BOOK, "Incredible Book");
    RegisterItemName(Fix.INCREDIBLE_ORB, "Incredible Orb");
    RegisterItemName(Fix.INCREDIBLE_LARGE_SWORD, "Incredible Greatsword");
    RegisterItemName(Fix.INCREDIBLE_LARGE_LANCE, "Incredible Grand Lance");
    RegisterItemName(Fix.INCREDIBLE_LARGE_AXE, "Incredible Grand Axe");
    RegisterItemName(Fix.INCREDIBLE_BOW, "Incredible Bow");
    RegisterItemName(Fix.INCREDIBLE_LARGE_STAFF, "Incredible Grand Staff");
    RegisterItemName(Fix.INCREDIBLE_SHIELD, "Incredible Shield");
    RegisterItemName(Fix.INCREDIBLE_ARMOR, "Incredible Armor");
    RegisterItemName(Fix.INCREDIBLE_CROSS, "Incredible Cross");
    RegisterItemName(Fix.INCREDIBLE_ROBE, "Incredible Robe");
    // --- Key / quest items ---
    RegisterItemName(Fix.ZETANIUM_STONE, "Zetanium Ore");
    RegisterItemName(Fix.FIELD_RESEARCH_LICENSE, "Expedition Permit");
    RegisterItemName(Fix.PURE_CLEAN_WATER, "Pure Clear Water");
    RegisterItemName(Fix.SHADOW_MOON_KEY, "Shadow Moon Key");
    RegisterItemName(Fix.SUN_BURST_KEY, "Sun Burst Key");
    RegisterItemName(Fix.STAR_DUST_KEY, "Star Dust Key");
    RegisterItemName(Fix.ORIGIN_ROAD_KEY, "Origin Road Key");
    RegisterItemName(Fix.RESIST_POISON_SUIT, "Poison-Resistant Suit");
    RegisterItemName(Fix.ARTHARIUM_KEY, "Artharium Factory Key");
    RegisterItemName(Fix.UNKNOWN_OBJECT, "Strange Object");
    RegisterItemName(Fix.MARBLE_STAR, "Marble Star");
    RegisterItemName(Fix.ZHALMAN_NECKLACE, "Zhalman Village Necklace");
    RegisterItemName(Fix.FIRE_ANGEL_TALISMAN, "Flame-Blessed Angel's Talisman");
    RegisterItemName(Fix.EARRING_OF_LANA, "Lana's Earring");
    RegisterItemName(Fix.PRECIOUS_SWORD, "Precious Sword ???");
    RegisterItemName(Fix.BLUESKY_STAR_FEATHER, "Blue Starlit Heaven Feather");
    RegisterItemName(Fix.REDCOMET_STAR_CHARM, "Red Comet Star Charm");
    // --- Black Materials ---
    RegisterItemName(Fix.POOR_BLACK_MATERIAL, "Black Material");
    RegisterItemName(Fix.POOR_BLACK_MATERIAL2, "Black Material [Revised]");
    RegisterItemName(Fix.POOR_BLACK_MATERIAL3, "Black Material [Ash]");
    RegisterItemName(Fix.POOR_BLACK_MATERIAL4, "Black Material [Dense]");
    RegisterItemName(Fix.POOR_BLACK_MATERIAL5, "Black Material [Dust]");
    RegisterItemName(Fix.POOR_BLACK_MATERIAL6, "Black Material [Trial]");
    RegisterItemName(Fix.POOR_BLACK_MATERIAL7, "Black Material [Ruin]");
    RegisterItemName(Fix.POOR_BLACK_MATERIAL8, "Black Material [Return]");
    RegisterItemName(Fix.POOR_BLACK_MATERIAL9, "Black Material [Void]");
    // --- Potions ---
    RegisterItemName(Fix.SMALL_RED_POTION, "Small Red Potion");
    RegisterItemName(Fix.SMALL_BLUE_POTION, "Small Blue Potion");
    RegisterItemName(Fix.SMALL_GREEN_POTION, "Small Green Potion");
    RegisterItemName(Fix.NORMAL_RED_POTION, "Red Potion");
    RegisterItemName(Fix.NORMAL_BLUE_POTION, "Blue Potion");
    RegisterItemName(Fix.NORMAL_GREEN_POTION, "Green Potion");
    RegisterItemName(Fix.LARGE_RED_POTION, "Large Red Potion");
    RegisterItemName(Fix.LARGE_BLUE_POTION, "Large Blue Potion");
    RegisterItemName(Fix.LARGE_GREEN_POTION, "Large Green Potion");
    RegisterItemName(Fix.HUGE_RED_POTION, "Huge Red Potion");
    RegisterItemName(Fix.HUGE_BLUE_POTION, "Huge Blue Potion");
    RegisterItemName(Fix.HUGE_GREEN_POTION, "Huge Green Potion");
    RegisterItemName(Fix.HQ_RED_POTION, "High-Quality Red Potion");
    RegisterItemName(Fix.HQ_BLUE_POTION, "High-Quality Blue Potion");
    RegisterItemName(Fix.HQ_GREEN_POTION, "High-Quality Green Potion");
    RegisterItemName(Fix.THQ_RED_POTION, "Supreme Red Potion");
    RegisterItemName(Fix.THQ_BLUE_POTION, "Supreme Blue Potion");
    RegisterItemName(Fix.THQ_GREEN_POTION, "Supreme Green Potion");
    RegisterItemName(Fix.PERFECT_RED_POTION, "Perfect Red Potion");
    RegisterItemName(Fix.PERFECT_BLUE_POTION, "Perfect Blue Potion");
    RegisterItemName(Fix.PERFECT_GREEN_POTION, "Perfect Green Potion");
    RegisterItemName(Fix.POTION_RESIST_FIRE, "Heat Resist Potion");
    RegisterItemName(Fix.CURE_SEAL, "Cure Seal");
    RegisterItemName(Fix.POTION_MAGIC_SEAL, "Magic Seal Potion");
    RegisterItemName(Fix.POTION_RESIST_PLUS, "Resist Potion Plus");
    RegisterItemName(Fix.PATERMA_DISMAGIC_DRINK, "Paterma Anti-Magic Drink");
    RegisterItemName(Fix.OLDTREE_GUARDIAN_MARK, "Ancient Great Tree Guardian Seal");
    RegisterItemName(Fix.LEKS_MYSTICAL_POTION, "Leks Mystical Potion");
    RegisterItemName(Fix.SEAL_OF_ARCPOWER, "Seal of Arc Power");
    RegisterItemName(Fix.SEAL_OF_CHOSEN_POWER, "Seal of Chosen Power");
    // --- Growth Elixirs ---
    RegisterItemName(Fix.GROWTH_LIQUID_STRENGTH, "Growth Elixir [Strength]");
    RegisterItemName(Fix.GROWTH_LIQUID_AGILITY, "Growth Elixir [Agility]");
    RegisterItemName(Fix.GROWTH_LIQUID_INTELLIGENCE, "Growth Elixir [Intelligence]");
    RegisterItemName(Fix.GROWTH_LIQUID_STAMINA, "Growth Elixir [Stamina]");
    RegisterItemName(Fix.GROWTH_LIQUID_MIND, "Growth Elixir [Spirit]");
    RegisterItemName(Fix.GROWTH_LIQUID2_STRENGTH, "Growth Elixir II [Strength]");
    RegisterItemName(Fix.GROWTH_LIQUID2_AGILITY, "Growth Elixir II [Agility]");
    RegisterItemName(Fix.GROWTH_LIQUID2_INTELLIGENCE, "Growth Elixir II [Intelligence]");
    RegisterItemName(Fix.GROWTH_LIQUID2_STAMINA, "Growth Elixir II [Stamina]");
    RegisterItemName(Fix.GROWTH_LIQUID2_MIND, "Growth Elixir II [Spirit]");
    RegisterItemName(Fix.GROWTH_LIQUID3_STRENGTH, "Growth Elixir III [Strength]");
    RegisterItemName(Fix.GROWTH_LIQUID3_AGILITY, "Growth Elixir III [Agility]");
    RegisterItemName(Fix.GROWTH_LIQUID3_INTELLIGENCE, "Growth Elixir III [Intelligence]");
    RegisterItemName(Fix.GROWTH_LIQUID3_STAMINA, "Growth Elixir III [Stamina]");
    RegisterItemName(Fix.GROWTH_LIQUID3_MIND, "Growth Elixir III [Spirit]");
    RegisterItemName(Fix.GROWTH_LIQUID4_STRENGTH, "Growth Elixir IV [Strength]");
    RegisterItemName(Fix.GROWTH_LIQUID4_AGILITY, "Growth Elixir IV [Agility]");
    RegisterItemName(Fix.GROWTH_LIQUID4_INTELLIGENCE, "Growth Elixir IV [Intelligence]");
    RegisterItemName(Fix.GROWTH_LIQUID4_STAMINA, "Growth Elixir IV [Stamina]");
    RegisterItemName(Fix.GROWTH_LIQUID4_MIND, "Growth Elixir IV [Spirit]");
    RegisterItemName(Fix.GROWTH_LIQUID5_STRENGTH, "Growth Elixir V [Strength]");
    RegisterItemName(Fix.GROWTH_LIQUID5_AGILITY, "Growth Elixir V [Agility]");
    RegisterItemName(Fix.GROWTH_LIQUID5_INTELLIGENCE, "Growth Elixir V [Intelligence]");
    RegisterItemName(Fix.GROWTH_LIQUID5_STAMINA, "Growth Elixir V [Stamina]");
    RegisterItemName(Fix.GROWTH_LIQUID5_MIND, "Growth Elixir V [Spirit]");
    RegisterItemName(Fix.GROWTH_LIQUID6_STRENGTH, "Growth Elixir VI [Strength]");
    RegisterItemName(Fix.GROWTH_LIQUID6_AGILITY, "Growth Elixir VI [Agility]");
    RegisterItemName(Fix.GROWTH_LIQUID6_INTELLIGENCE, "Growth Elixir VI [Intelligence]");
    RegisterItemName(Fix.GROWTH_LIQUID6_STAMINA, "Growth Elixir VI [Stamina]");
    RegisterItemName(Fix.GROWTH_LIQUID6_MIND, "Growth Elixir VI [Spirit]");
    RegisterItemName(Fix.GROWTH_LIQUID7_STRENGTH, "Growth Elixir VII [Strength]");
    RegisterItemName(Fix.GROWTH_LIQUID7_AGILITY, "Growth Elixir VII [Agility]");
    RegisterItemName(Fix.GROWTH_LIQUID7_INTELLIGENCE, "Growth Elixir VII [Intelligence]");
    RegisterItemName(Fix.GROWTH_LIQUID7_STAMINA, "Growth Elixir VII [Stamina]");
    RegisterItemName(Fix.GROWTH_LIQUID7_MIND, "Growth Elixir VII [Spirit]");
    // --- Common material drops ---
    RegisterItemName(Fix.COMMON_MANDORAGORA_ROOT, "Mandragora Root");
    RegisterItemName(Fix.COMMON_WOLF_FUR, "Wolf Pelt");
    RegisterItemName(Fix.COMMON_ANT_ESSENCE, "Ant Essence");
    RegisterItemName(Fix.COMMON_SUN_LEAF, "Sun Leaf");
    RegisterItemName(Fix.COMMON_RABBIT_MEAT, "Rabbit Meat");
    RegisterItemName(Fix.COMMON_ORANGE_MATERIAL, "Orange Material");
    RegisterItemName(Fix.COMMON_ASH_EGG, "Pale Gray Egg");
    RegisterItemName(Fix.COMMON_PLANTNOID_SEED, "Plantnoid Seed");
    RegisterItemName(Fix.COMMON_MACHINE_PARTS, "Machine Parts");
    RegisterItemName(Fix.COMMON_BAT_FEATHER, "Bat Wing");
    RegisterItemName(Fix.COMMON_GLASS_SHARD, "Glass Shard");
    RegisterItemName(Fix.COMMON_MECHANICAL_SHAFT, "Mechanical Shaft");
    RegisterItemName(Fix.COMMON_AMBER_MATERIAL, "Amber Material");
    RegisterItemName(Fix.COMMON_SOLIDSTONE_MATERIAL, "Hard Stone Material");
    RegisterItemName(Fix.COMMON_JUNK_PARTS, "Junk Parts");
    RegisterItemName(Fix.COMMON_ELECT_BOLT, "Electromagnetic Bolt");
    RegisterItemName(Fix.COMMON_GARGOYLE_EYE, "Gargoyle Eyeball");
    RegisterItemName(Fix.COMMON_WATCHDOG_TONGUE, "Watchdog Tongue");
    RegisterItemName(Fix.COMMON_CHROTIUM_MATERIAL, "Chrotium Material");
    RegisterItemName(Fix.COMMON_MIST_LEAF, "Mist Grass");
    RegisterItemName(Fix.COMMON_NORMAL_SPORE_ESSENCE, "Unprocessed Spore Extract");
    RegisterItemName(Fix.COMMON_FROG_FRONTLEG, "Frog Foreleg");
    RegisterItemName(Fix.COMMON_BEAR_LARGE_CLAW, "Bear's Great Claw");
    RegisterItemName(Fix.COMMON_FAIRY_POWDER, "Fairy Powder");
    RegisterItemName(Fix.COMMON_BEAUTY_WHITEFEATHER, "Beautiful White Feather");
    RegisterItemName(Fix.COMMON_HUNTER_TOOL, "Hunter's Tool Bag");
    RegisterItemName(Fix.COMMON_BLACK_MIST_ESSENCE, "Black Mist Extract");
    RegisterItemName(Fix.COMMON_ELEPHANT_LEGS, "Elephant's Massive Legs");
    RegisterItemName(Fix.COMMON_LAPTOR_FUR, "Raptor Pelt");
    RegisterItemName(Fix.COMMON_SHARPNESS_TIGER_TOOTH, "Razor-Sharp Tiger Fang");
    RegisterItemName(Fix.COMMON_THORN_ELEMENT, "Thorn Crown Material");
    RegisterItemName(Fix.COMMON_MARY_KISS, "Mary Kiss");
    RegisterItemName(Fix.COMMON_MAGIC_HORN, "Magic Horn");
    RegisterItemName(Fix.COMMON_WINDMAN_SEAL, "Wind Folk's Seal");
    RegisterItemName(Fix.COMMON_MYSTERY_SCROLL, "Mysterious Scroll");
    RegisterItemName(Fix.COMMON_BLUECOLOR_EYE, "Blue Eyeball");
    RegisterItemName(Fix.COMMON_WHITECOLOR_EYE, "White Eyeball");
    RegisterItemName(Fix.COMMON_CURTAIN_MATERIAL, "Curtain Material");
    RegisterItemName(Fix.COMMON_ARTHARIUM_JEWEL, "Artharium Jewel");
    RegisterItemName(Fix.COMMON_LION_FUR, "Lion Pelt");
    RegisterItemName(Fix.COMMON_PARTIMIUM_MATERIAL, "Partimium Material");
    RegisterItemName(Fix.COMMON_HUGE_BOOK, "Thick Tome");
    RegisterItemName(Fix.COMMON_GUNPOWDER, "Gunpowder");
    RegisterItemName(Fix.COMMON_SILENT_WHISTLE, "Silent Whistle");
    RegisterItemName(Fix.COMMON_STEEL_BATON, "Steel Baton");
    RegisterItemName(Fix.COMMON_PURE_SILVER, "Pure Silver");
    RegisterItemName(Fix.COMMON_SPEEDARROW_TOOL, "Swift Arrow Crafting Tool");
    RegisterItemName(Fix.COMMON_OVAL_GEAR, "Oval Gear");
    RegisterItemName(Fix.COMMON_APLITOS_BONE, "Aplitos Cartilage");
    RegisterItemName(Fix.COMMON_DEATH_CLOVER, "Death Clover");
    RegisterItemName(Fix.COMMON_JUMP_MATERIAL, "Jumping Material");
    RegisterItemName(Fix.COMMON_BIG_STONE, "Big Stone");
    RegisterItemName(Fix.COMMON_UNKNOWN_BOX, "Unidentified Box");
    RegisterItemName(Fix.RARE_JOE_TONGUE, "Joe's Tongue");
    RegisterItemName(Fix.COMMON_SEA_WATER, "Pure Seawater");
    RegisterItemName(Fix.COMMON_SEA_MUSICBOX, "Sea Music Box");
    RegisterItemName(Fix.RARE_MEPHISTO_BLACKLIGHT, "Mephisto's Black Flame");
    RegisterItemName(Fix.COMMON_SEEKER_HEAD, "Seeker's Skull");
    RegisterItemName(Fix.RARE_ESSENCE_OF_DARK, "Essence of Dark");
    RegisterItemName(Fix.COMMON_EXECUTIONER_ROBE, "Executioner's Tattered Robe");
    RegisterItemName(Fix.COMMON_NEMESIS_ESSENCE, "Nemesis Essence");
    RegisterItemName(Fix.RARE_MASTERBLADE_FIRE, "Masterblade's Embers");
    RegisterItemName(Fix.COMMON_GREAT_JEWELCROWN, "Grand Jewel Crown");
    RegisterItemName(Fix.RARE_ESSENCE_OF_SHINE, "Essence of Shine");
    RegisterItemName(Fix.RARE_DEMON_HORN, "Demon Horn");
    RegisterItemName(Fix.COMMON_WYVERN_BONE, "Wyvern Bone");
    RegisterItemName(Fix.RARE_ESSENCE_OF_FLAME, "Essence of Flame");
    RegisterItemName(Fix.RARE_BLACK_SEAL_IMPRESSION, "Black Seal Imprint");
    RegisterItemName(Fix.COMMON_HIGH_ESTORMIUM_MATERIAL, "High-Purity Estormium Material");
    RegisterItemName(Fix.RARE_ANGEL_SILK, "Angel's Silk");
    RegisterItemName(Fix.RARE_DREAD_EXTRACT, "Dread Extract");
    RegisterItemName(Fix.COMMON_ESSENCE_OF_WIND, "Essence of Wind");
    RegisterItemName(Fix.COMMON_INNOCENCE_ESSENCE, "Innocence Essence");
    RegisterItemName(Fix.COMMON_UNRESOLVED_MATERIAL, "Unidentified Substance");
    // --- Item category labels ---
    RegisterItemName(Fix.DESCRIPTION_SELL_ONLY, "For Sale Only");
    RegisterItemName(Fix.DESCRIPTION_BATTLE_ONLY, "Battle Use Only");
    RegisterItemName(Fix.DESCRIPTION_EQUIP_MATERIAL, "Weapon Material");
    RegisterItemName(Fix.DESCRIPTION_POTION_MATERIAL, "Potion Material");
    RegisterItemName(Fix.DESCRIPTION_FOOD_MATERIAL, "Food Ingredient");
    RegisterItemName(Fix.DESCRIPTION_WEAPON, "Weapon");
    RegisterItemName(Fix.DESCRIPTION_SHIELD, "Shield");
    RegisterItemName(Fix.DESCRIPTION_ARMOR, "Armor");
    RegisterItemName(Fix.DESCRIPTION_ACCESSORY, "Accessory");
    RegisterItemName(Fix.DESCRIPTION_POTION, "Consumable");
    RegisterItemName(Fix.DESCRIPTION_BLUEORB, "Exclusive Item");
    // --- Special named items (already English values) ---
    // NAME_SIN_OSCURETE は人物名だが Item.cs にも case があるため、ここで対訳を持つ。
    RegisterItemName(Fix.NAME_SIN_OSCURETE, "Sin Oscurete");
    RegisterItemName(Fix.RING_OF_OSCURETE, "Ring of the Oscurete");
    RegisterItemName(Fix.MERGIZD_SOL_BLADE, "Mergizd Sol Blade");
    RegisterItemName(Fix.ADILORB_OF_THE_GARVANDI, "AdilOrb of the Garvandi");
    RegisterItemName(Fix.MAXCARN_X_BUSTER, "Maxcarn the X-BUSTER");
    RegisterItemName(Fix.GATUH_HAWL_OF_GREAT, "Gatuh Hawl of Great");
    RegisterItemName(Fix.JUZA_ARESTINE_SLICER, "Arestine-Slicer of Juza");
    RegisterItemName(Fix.ADILRING_OF_BLUE_BURN, "AdilRing of the Blue Burn");
    RegisterItemName(Fix.SHEZL_MYSTIC_FORTUNE, "Shezl the Mystic Fortune");
    RegisterItemName(Fix.FLOW_FUNNEL_OF_THE_ZVELDOZE, "Flow Funnel of the Zveldose");
    RegisterItemName(Fix.EZEKRIEL_IMPRINT_SIGIL_ARMOR, "Ezekriel the Imprinted-Armor of Sigil");
    RegisterItemName(Fix.MERGIZD_DAV_AGITATED_BLADE, "Mergizd DAV-Agitated Blade");
    RegisterItemName(Fix.SHEZL_THE_VENTIEL_DARKMIRAGE_BOOK, "Shezl the Ventiel-DarkMirage Book");
    RegisterItemName(Fix.XEXXER_WORLD_MASTERY_GLOBE, "Xexxer the World-Mastery Globe");
    // ---------------------------------------------------------------
  }
}
